### PR TITLE
Add support for EliteBook8570p

### PR DESCRIPTION
**Pull request by Memphiz**
Hi RehabMan,

as i am ill in the moment and have some time *well haha* - i figured that the PBI tool is not maintained anymore. Well at least for my AMD GPU based elitebook 8570p i figured out your hotpatch method (i think).

Not sure if you want to add this to your master branch - but i thought i would at least try and share it with you.

The mount_efi commit is nice to have anyways i think because in 10.11 all disks are done via Core Storage...

This was tested on a HP EliteBook 8570p with AMD Radeon HD 7570M (1600x900), 8GB RAM, 512GB SSD, Corei7-3630QM running both osx 10.9.5 (Mavericks) and osx 10.11.4 (ElCapitan) using latest HP BIOS F.62A.

Everything works including webcam and sdcard reader. The only thing that doesn't work is wakeup after sleep on 10.11.4 (comes up with black screen only) - which works fine on 10.9.5. If you have any idea how to track that one down it would be very welcome. (increasing the brightness in that state doesn't fix it ...) And DisplayPort Audio doesn't work aswell (though i injected the layout id into the HDAU device but just blindly).

For the readme on what to do to generate the needed bits for EliteBook 81570p:
copy the bin from rom/ to /Volumes/EFI/EFI/CLOVER/ROM
use SSDT-HACK.aml SSDT-BATT.aml SSDT-FAN-something.aml SSDT-KEY102.aml SSDT-AMDGPU-aml
use config/config_8570p_amd.plist

layout injection via the devices/arbitrary key in the config.plist doesn't seem to work thats why i did it via ssdt.

Hope you read that bit wall of text :D - and thx a thousand bunches for all the work you do for making osx on those hp notebooks such a nice experience.

For reference here is the usual debug stuff from my hackbook with all this configs applied:

https://www.dropbox.com/sh/1m29genjse428bc/AABvQn5mbMtbcxL7RVwMLSSia?dl=0

### CODE REVIEW

**Comment by Memphiz** [comment]
nevermind about the black screen after wakeup - i think its well known for month and without solution yet and specific to el capitan and amd drivers/framebuffers:

https://sourceforge.net/p/cloverefiboot/discussion/1726372/thread/8628f006/

Good i kept mavericks as my main os version :)

**Comment by Memphiz** [comment]
force-pushe ATI inject including the vbios is done via config.plist only now (rom is embedded in base64 data). No SSDT changes needed. USB is identical to 6x70...

**Comment by RehabMan** [comment]
Just saw this now after doing a massive refactor of the project.
Can you re-apply the few changes you need into the new structure?
I'll be happy to look at it then.

And... I suppose caveat is install 10.10 or 10.9 not 10.11... (because of AMD wakeup bug).

**Comment by RehabMan** [comment]
If not, I can probably manually merge, including creating the new required SSDTs...
You might be able to boot without -xcpm if you drop MCFG.

**Comment by Memphiz** [comment]
I'll try to do so once i have spare time again (might be a couple of weeks).

**Comment by RehabMan** [comment]
FYI: I switched from /Devices/Arbitrary to an SSDT/_DSM injection approach because too many people didn't read the guide and would edit their config.plist with Clover Configurator, which of course, deletes /Devices/Arbitrary.  Got tried of wasting my time looking at files clearly damaged from people not heeding precise advice.

There is still the case of Clover Configurator re-ordering the entries in KextsToPatch (which can be, and are Order dependent)...  But I plan to fix the one case of order dependency today (DONE).

**Comment by Memphiz** [comment]
@RehabMan sorry - i won't do anything in the regard of AMD support because i switched my system board to also have intel gpu. This gives me all the cool stuff without tinkering with AMD anymore (and with the wake from sleep bug - it was really annoying). So i am in the intel world too now (which you support in a great way btw).

**Comment by Memphiz** [comment]
@RehabMan but you really want to cherry-pick this one

https://github.com/RehabMan/HP-ProBook-4x30s-DSDT-Patch/pull/3/commits/eee72fd960560d013b1b368efc4b453172af8bec

because mount_efi doesn't work on el capitan as is ...

**Comment by RehabMan** [comment]
mount_efi.sh works just fine if you follow the guide.  I never end up with core storage when I partition as per guide.

But I  will look at your changes and test it with the normal install method.

Closing this pull due to no interest in AMD/Radeon...

**Pull request closed without merging**
